# Generated by Django 5.1.2 on 2025-05-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablemodel',
            unique_together={('id',)},
        ),
        migrations.RemoveField(
            model_name='tablemodel',
            name='number',
        ),
    ]
