# Generated by Django 5.1.2 on 2025-05-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_tablemodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablemodel',
            unique_together=set(),
        ),
    ]
