# Generated by Django 5.1.2 on 2024-10-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('drinks', 'Drinks'), ('alcohol_drinks', 'Alcohol Drinks'), ('starters', 'Starters'), ('breakfasts', 'Breakfasts'), ('meals', 'Meals'), ('desserts', 'Desserts'), ('extras', 'Extras')], default='undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
