# Generated by Django 5.1.2 on 2024-10-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_category_alter_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customers_numbers',
            field=models.IntegerField(default=1),
        ),
    ]
