# Generated by Django 5.1.2 on 2025-01-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_ingredientmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('TRANSACTION', 'Transaction')], max_length=20, null=True),
        ),
    ]
