# Generated by Django 5.1.2 on 2024-10-28 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_stocktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='stock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='restaurant.stock'),
        ),
    ]
