# Generated by Django 5.1.2 on 2025-01-02 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_paymentmodel_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 4, 42, 20, 899535, tzinfo=datetime.timezone.utc)),
        ),
    ]
