# Generated by Django 5.1.2 on 2025-01-02 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_paymentmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
