# Generated by Django 5.1.2 on 2024-10-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_stock_ingredient_ingredient_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='ingredient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='restaurant.ingredient'),
        ),
    ]
