# Generated by Django 5.1.2 on 2025-01-03 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_paymentmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodel',
            name='category',
            field=models.CharField(choices=[('DRINKS', 'Drinks'), ('ALCOHOL_DRINKS', 'Alcohol Drinks'), ('BREAKFASTS', 'Breakfasts'), ('STARTERS', 'Starters'), ('MEALS', 'Meals'), ('DESSERTS', 'Desserts'), ('EXTRAS', 'Extras')]),
        ),
        migrations.AlterField(
            model_name='paymentitemmodel',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='restaurant.paymentmodel'),
        ),
    ]
