# Generated by Django 5.1.2 on 2025-01-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_menuitemmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodel',
            name='category',
            field=models.CharField(choices=[('DRINKS', 'Drinks'), ('ALCOHOL_DRINKS', 'Alcohol Drinks'), ('BREAKFASTS', 'Breakfasts'), ('STARTERS', 'Starters'), ('MEALS', 'Meals'), ('DESSERTS', 'Desserts'), ('EXTRAS', 'Extras')], max_length=20),
        ),
    ]
