# Generated by Django 5.1.2 on 2024-10-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='VAT',
            field=models.DecimalField(decimal_places=2, default=0.16, max_digits=4),
        ),
    ]
